### ISSUE TITLE
Error with digitalocean 

### ISSUE THREAD

**Issue by Nhoty** [Coalfire-Research/Red-Baron#5] opened 2018-02-27 20:35 UTC
When 
```
$ terraform apply
 
Error: Error applying plan:

4 error(s) occurred:

* module.dns_rdir.digitalocean_ssh_key.ssh_key: 1 error(s) occurred:

* digitalocean_ssh_key.ssh_key: Error creating SSH Key: invalid character '<' looking for beginning of value
* module.dns_c2.digitalocean_ssh_key.ssh_key: 1 error(s) occurred:

* digitalocean_ssh_key.ssh_key: Error creating SSH Key: invalid character '<' looking for beginning of value
* module.http_rdir.digitalocean_ssh_key.ssh_key: 1 error(s) occurred:

* digitalocean_ssh_key.ssh_key: Error creating SSH Key: invalid character '<' looking for beginning of value
* module.http_c2.digitalocean_ssh_key.ssh_key: 1 error(s) occurred:

* digitalocean_ssh_key.ssh_key: Error creating SSH Key: invalid character '<' looking for beginning of value
```

I find this , I dont know if it help somehow .
https://github.com/digitalocean/godo/issues/142

Cheers .

**Comment by byt3bl33d3r** [comment] 2018-02-28 16:45
Seems like it's a bug in the provder itself, what Terraform version are you using?

**Comment by Nhoty** [comment] 2018-02-28 23:35
The last one.

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by byt3bl33d3r** [comment] 2018-08-23 23:41
Closing since the mentioned issue seems to be fixed and I cannot reproduce it.

**Closed by byt3bl33d3r** 2018-08-23 23:41 UTC
Labels: bug, third-party
